version: "3"

services:
  db:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=nomebanco"
    ports:
      - 5432:5432
